//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subject_Selection.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Subject_Selection.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Bachelor of Actuarial Studies	C000117
        ///
        ///Owner:			Macquarie Business School
        ///Owner:			Macquarie University
        ///Award:				Bachelor of Actuarial Studies (BActStud)
        ///Core Zone
        ///
        ///
        ///Capstone unit	Credit Points
        ///Essential		ACST3059		Actuarial Modelling (10)	10
        ///
        ///Essential units	 
        ///Essential		ACST1052		Introduction to Actuarial Studies (10)	10
        ///Essential		ECON1020		Principles of Economics 1 (10)	10
        ///Essential		ECON1021		Principles of Economics 2 (10)	10
        ///Essential		MATH1025		Mathematical Modelling IB (Advanced) ( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2020_ScheduleOfCoursesUG {
            get {
                return ResourceManager.GetString("_2020_ScheduleOfCoursesUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Faculty of Arts
        ///
        ///Ancient Egypt and the Near East	N000047
        ///
        ///Faculty:	Faculty of Arts
        ///Department:	 
        ///
        ///This major must be completed as part of an award. The general requirements for the award must be satisfied in order to graduate.
        ///
        ///Requirements:
        ///
        ///
        ///Essential units	Credit Points
        ///Essential		AHIS1240		Ancient Israel and the Near East (10)	10
        ///Essential		AHIS1250		Ancient Egyptian Archaeology (10)	10
        ///Essential		AHIS2000		Sources and Methodology in Ancient History (10)	10
        ///Essential		AHIS3001		Materia [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2020_ScheduleOfMajors {
            get {
                return ResourceManager.GetString("_2020_ScheduleOfMajors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Faculty of Arts
        ///
        ///Chinese International Studies	Q000230
        ///
        ///Faculty:	Faculty of Arts
        ///Department:	 
        ///
        ///This specialisation must be completed as part of an award. The general requirements for the award must be satisfied in order to graduate.
        ///
        ///Requirements:
        ///
        ///
        ///Essential units	Credit Points
        ///Essential		INTS3000		International Studies In-Country Program (40)	40
        ///
        ///Elective units	 
        ///Option set	20cp from 	CHIN units at 1000 level	
        ///		INTS1020		China in World History (10)	20
        ///Option set	10cp from 	CHIN units [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2020_ScheduleOfUGSpecialisations {
            get {
                return ResourceManager.GetString("_2020_ScheduleOfUGSpecialisations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Scope,Code,Name,&quot;Credit
        ///Points&quot;,Unit Designation,Unit Type,Prerequisites,Corequisites,NCCW,When Offered,On Campus Attendance,Staff Contact,&quot;Offering
        ///Department&quot;,Offering Faculty,&quot;FOE -
        ///Narrow&quot;,Pass/Fail,Co-taught Units,Quota,Unit Activity,ASQCNew,ASQCRecoded,WWCC,Status,Placement in SONIA,Authority,Capstone unit?,Awards/Majors
        ///Undergraduate,ABST1000,Introducing Indigenous Australia,10,,,,,&quot;ABSP100, ABST100&quot;,&quot;S1 Day
        ///S1 Online
        ///S2 Day
        ///S2 Online&quot;,&quot;
        ///
        ///
        ///&quot;,&quot;Ms Josephine Bourne
        ///        ///&quot;,Department of Indigenous Stud [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScheduleOfUndergraduateUnits {
            get {
                return ResourceManager.GetString("ScheduleOfUndergraduateUnits", resourceCulture);
            }
        }
    }
}
