//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subject_Selection.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Subject_Selection.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule of Courses of Study 2020
        ///
        ///Macquarie University
        ///
        ///Bachelor of Actuarial Studies	C000117
        ///
        ///Owner:			Macquarie Business School
        ///Owner:			Macquarie University
        ///Award:				Bachelor of Actuarial Studies (BActStud)
        ///Core Zone
        ///
        ///
        ///Capstone unit	Credit Points
        ///Essential		ACST3059		Actuarial Modelling (10)	10
        ///
        ///Essential units	 
        ///Essential		ACST1052		Introduction to Actuarial Studies (10)	10
        ///Essential		ECON1020		Principles of Economics 1 (10)	10
        ///Essential		ECON1021		Principles of Economics 2 (10)	10
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2020_ScheduleOfCoursesUG {
            get {
                return ResourceManager.GetString("_2020_ScheduleOfCoursesUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEB18V1|COMP115 COMP125 DMTH137 ISYS114 MAS_110 COMP249 ISYS224 MAS_241 COMP344 COMP348 ISYS358 MAS_340
        ///DES18V1|(STAT150 OR STAT170 OR STAT171) STAT279 (STAT270 OR STAT271) (STAT272 OR STAT273 OR STAT278) STAT399 STAT321 STAT379 (STAT302 OR STAT328)
        ///CMP18V1|(6CP COMP100-199 ISYS100-199) (6CP COMP200-299 ISYS200-299) ISYS358 (9CP COMP300-350 ISYS300-350 ISYS360)
        ///STA18V1|(STAT150 OR STAT170 OR STAT171) (STAT270 OR STAT271) (STAT272 OR STAT273) (STAT278 OR STAT279) STAT399 STAT375 (6CP STAT302 STAT306 STAT3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Majors {
            get {
                return ResourceManager.GetString("Majors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Scope,Code,Name,&quot;Credit
        ///Points&quot;,Unit Designation,Unit Type,Prerequisites,Corequisites,NCCW,When Offered,On Campus Attendance,Staff Contact,&quot;Offering
        ///Department&quot;,Offering Faculty,&quot;FOE -
        ///Narrow&quot;,Pass/Fail,Co-taught Units,Quota,Unit Activity,ASQCNew,ASQCRecoded,WWCC,Status,Placement in SONIA,Authority,Capstone unit?,Awards/Majors
        ///Undergraduate,ABST1000,Introducing Indigenous Australia,10,,,,,&quot;ABSP100, ABST100&quot;,&quot;S1 Day
        ///S1 Online
        ///S2 Day
        ///S2 Online&quot;,&quot;
        ///
        ///
        ///&quot;,&quot;Ms Josephine Bourne
        ///        ///&quot;,Department of Indigenous Stud [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScheduleOfUndergraduateUnits {
            get {
                return ResourceManager.GetString("ScheduleOfUndergraduateUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMP111|3|S2D||INFO111 MAS111
        ///COMP115|3|S1D S1E S3D||COMP124 COMP155 ITEC100
        ///COMP125|3|S1E S2D|COMP115|COMP165
        ///COMP188|3|FY1D S1D S2D||
        ///COMP202|3|S2D|COMP125|COMP226
        ///COMP225|3|S1D|COMP125 AND (3CP MATH132-136 DMTH137 STAT150 STAT170 STAT171 STAT175)|ITEC200
        ///COMP229|3|S2D|COMP125|ITEC200
        ///COMP247|3|S1D|COMP115 OR ISYS114|COMP327 COMP341 ITEC102
        ///COMP249|3|S1D|COMP125 ISYS114|ITEC301
        ///COMP255|3|S2D|(18CP *100+) COMP125|COMP227 ISYS227 ITEC202
        ///COMP257|3|S2D|(COMP115 OR COMP125) AND (STAT150 OR STAT170 O [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
    }
}
